### ISSUE TITLE
Incomplete results

### ISSUE THREAD

**Issue by apaytuvi** [iquasere/UPIMAPI#3]
Good morning,

I've check the new version of UPIMAPI and now connects well to UniProt API. Nevertheless, I got unexpected results. I have a list of proteins, more than a million, and the API of UniProt says the list of proteins is too long. Didn't UPIMAPI retrieve the information in batches?

In order to overcome this limitation, I've split the big list to small files containing a maximum of 100.000 proteins. After UPIMAPI, I only see results for a few of them (20-30). Why is that?

Thank you very much in advance.

Best,

**Comment by iquasere** [comment]
Hey there, @apaytuvi! And thank you for helping test the tool! I did not properly check the number of lines in the result, since a simple header looked fine and [so did the CI](https://github.com/iquasere/UPIMAPI/actions/runs/2601224730). Because of the new updates, one must now first obtain valid IDs before ID mapping, since the new API fails if it is submitted not valid IDs (and the notion of invalid is either outdated or "entry name" IDs, which before it simply ignored or converted to proper "entry" IDs).

I took the solution UniProt's help desk gave me at face value because it seemed to be working fine, but it is returning only the first page of results (25 IDs). Therefore, I am altering the tool to now split the IDs into requests 25 IDs at a time, so it gets those all mapped everytime.

I expect to have this working today! 🤞

**Comment by iquasere** [comment]
I believe it is fixed now, but ID conversion had to be reformatted into taking 25 IDs at a time, which takes a while. If you think you have no outdated IDs, you can skip this ID validation with ```--skip-id-checking``` parameter.

Also, it seems the requests can't take the same number of IDs at a time. For now, I would advise using ```--step 1000``` to limit the request URL. I'll make this the default value for now.

**Comment by apaytuvi** [comment]
Thank you!

I've just cloned the repository, tried it, but still get 25 rows as output.

**Comment by iquasere** [comment]
I dived a bit deeper into this new API, and believe now UPIMAPI obtains valid IDs for ID mapping as is supposed by the API creators. Still, the fact you only got 25 IDs at a time might be explained by the fact that, while you updated your git repo, it is not that UPIMAPI that you are running when running the ```upimapi.py``` command, but rather another script stored in your conda environment.

All of this mess will be sorted today or tomorrow. UPIMAPI 1.8 is still not available because it now requires geckodriver for web parsing the new UniProt (which was built in some JS framework, React or Vue, fml), and geckodriver requires firefox and friends, which only work when installed with apt. Since apt and conda are not compatible, UPIMAPI will now require an install script, that I'll be setting up in the next hours.

**Comment by iquasere** [comment]
UPIMAPI 1.8.1 should now have the same capabilities of 1.7 version (soon it will be available for install with ```conda install upimapi=1.8.1```), with the very annoying exception of Taxonomic columns - these are still not fixed by the UniProt team, as all Taxonomic comes bundled together in a ```Taxonomic lineage (ALL)``` column. Please, if the same problem persists, or you find other bugs, don't hesitate in reporting them, and thank you for helping with UPIMAPI.

For now I have to dedicate my time to finishing [MOSCA](https://github.com/iquasere/MOSCA), but if in a couple weeks the taxonomic problem is not fixed I'll implement a solution to transform that column into the proper separated columns.

**Comment by apaytuvi** [comment]
Good afternoon,

I still have the following error:

```
2022-07-12 15:20:03: ID mapping has begun.
Updating UniProt columns options
Auto determined "full id" as: False
Traceback (most recent call last):
  File "./UPIMAPI/upimapi.py", line 1168, in <module>
    upimapi()
  File "./UPIMAPI/upimapi.py", line 1146, in upimapi
    ids = get_valid_entries(ids, api_info)    # UniProt's API now fails if outdated IDs or entry names are submitted. This function removes those
  File "./UPIMAPI/upimapi.py", line 228, in get_valid_entries
    job_id = submit_id_mapping("UniProtKB_AC-ID", "UniProtKB", ids, api_info)
  File "./UPIMAPI/upimapi.py", line 210, in submit_id_mapping
    r.raise_for_status()
  File "/home/apaytuvi/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://rest.uniprot.org/idmapping/run
```

This is of course because my input have thousands of entries. When I get a subset of them, I get another error:

```
2022-07-12 15:20:54: ID mapping has begun.
Updating UniProt columns options
Auto determined "full id" as: False
Traceback (most recent call last):
  File "./UPIMAPI/upimapi.py", line 1168, in <module>
    upimapi()
  File "./UPIMAPI/upimapi.py", line 1146, in upimapi
    ids = get_valid_entries(ids, api_info)    # UniProt's API now fails if outdated IDs or entry names are submitted. This function removes those
  File "./UPIMAPI/upimapi.py", line 229, in get_valid_entries
    r = get_id_mapping_results(job_id, api_info)
  File "./UPIMAPI/upimapi.py", line 216, in get_id_mapping_results
    r = get_url(f"{api_info['servers'][0]['url']}/idmapping/status/{job_id}")
  File "./UPIMAPI/upimapi.py", line 184, in get_url
    response.raise_for_status()
  File "/home/apaytuvi/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error:  for url: https://rest.uniprot.org/idmapping/status/3d882a277dd613a39daa21887038636fdd7a97b8
```

Do you know what's going on?

**Comment by iquasere** [comment]
Could you please send me some input dataset that shows this happening? Also, are you using version 1.8.0 or 1.8.1?

**Comment by iquasere** [comment]
In 1.8.1 version I fixed the truncated input problem by iteratively searching through the pages of results from the same POST request. This should return all results, as it searches for the next page until the POST reports there is none left.

**Comment by apaytuvi** [comment]
Hi! Thank you for your availability!

The first error I pasted, the file used was the following one:
https://drive.google.com/file/d/14N-krji5XmbJUbP1fo_7mrmCgOTbbAE3/view?usp=sharing

Regarding the second error using the subset of protein sequences, now I tried again and it seems that is working fine. Maybe when I trieed the site was under maintenance or something like that.

Yes, I'm using version 1.8.1.

Thanks again!
Andreu

**Comment by iquasere** [comment]
Please check on version ```1.8.3``` when it is available - I already approved the [pull request](https://github.com/bioconda/bioconda-recipes/pull/35841) for it. Your pull request was right, but I have simplified that part of the code, it doesn't make sense now to keep the default columns on separate files, since this is a legacy from the time UPIMAPI had the ```columns_dictionary``` info in its files instead of web scraping. Now, everything should be working, as I have tested with your input and it successfully obtained information for all IDs.

**Comment by apaytuvi** [comment]
Good morning,

I'm using `1.8.3`. Nevertheless, this time it happens a weird thing:

![image](https://user-images.githubusercontent.com/11228225/179210103-64c9c7e6-ffee-48fd-907d-d20a2d0c75df.png)

Independently of the input number of proteins, it always retrieves 9998 proteins. I tried with version `1.8.2` and works well in this case. I cannot see anything that could cause this, looking at the changes in the code.

On the other hand, even with `1.8.3`, I still get this error:

```
python3 ./UPIMAPI/upimapi.py -i All_prodigal.prot.uniref.ids -o aa --no-annotation
2022-07-15 11:02:16: ID mapping has begun.
Updating UniProt columns options
Auto determined "full id" as: False
Traceback (most recent call last):
  File "./UPIMAPI/upimapi.py", line 1178, in <module>
    upimapi()
  File "./UPIMAPI/upimapi.py", line 1154, in upimapi
    ids = get_valid_entries(ids, api_info)    # UniProt's API now fails if outdated IDs or entry names are submitted. This function removes those
  File "./UPIMAPI/upimapi.py", line 233, in get_valid_entries
    job_id = submit_id_mapping("UniProtKB_AC-ID", "UniProtKB", ids, api_info)
  File "./UPIMAPI/upimapi.py", line 215, in submit_id_mapping
    r.raise_for_status()
  File "/home/apaytuvi/.local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Request Entity Too Large for url: https://rest.uniprot.org/idmapping/run
```

Thanks,

**Comment by iquasere** [comment]
I realized that I forgot to merge the [pull request](https://github.com/bioconda/bioconda-recipes/pull/35841) for 1.8.3.
Still, I haven't seen the error you are reporting since version 1.8.0. Are you sure it is the 1.8.3 version you are running? Please, try again to install it with ```conda/mamba install -c bioconda upimapi=1.8.3```. Also, don't forget to install the apt-get packages, with ```apt-get install packagekit-gtk3-module libasound2 libdbus-glib-1-2 libx11-xcb1```.
I added a test for a long list of IDs (as I should have a long time ago), and this version [is working fine](https://github.com/iquasere/UPIMAPI/runs/7359588231).

**Comment by apaytuvi** [comment]
Good morning,

I've just created a fresh conda environment and installed version 1.8.3. This is what I get:

![image](https://user-images.githubusercontent.com/11228225/180724982-2f05b42f-f238-4309-bdc2-0bf4c579f511.png)

As you can see, the input list is 176853, but UPIMAPI only retrieves 9998 proteins.

Thanks again for your time,
Andreu

**Comment by iquasere** [comment]
Yes, I am seeing this now. It's some problem in the validation of IDs, UPIMAPI now is forced to obtain a list of IDs valid for ID mapping before mapping, and it is not doing it correctly. I'm now trying to solve this

**Comment by iquasere** [comment]
This should be fixed in [UPIMAPI 1.8.4](https://github.com/iquasere/UPIMAPI/releases/tag/1.8.4). I have tested with the long list of IDs you sent, and it was successful. Do note that the tool now takes way longer than before, because for some reason UniProt's API now only accepts 1000 IDs per request...
